server:
  port: 8080

spring:
  profiles:
    active: dev

  data:
    redis:
      host: ${rag-gdgs.redis.host}
      port: ${rag-gdgs.redis.port}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rag_gdgs?serverTimezone=Asia/Shanghai&useSSL=false
    username: ${rag-gdgs.datasource.username}
    password: ${rag-gdgs.datasource.password}

  rabbitmq:
    host: ${rag-gdgs.rabbitmq.host}
    port: ${rag-gdgs.rabbitmq.port}
    username: ${rag-gdgs.rabbitmq.username}
    password: ${rag-gdgs.rabbitmq.password}
    virtual-host: /rag-gdgs


langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${rag-gdgs.langchain4j.open-ai.chat-model.api-key}
      model-name: qwen-plus
      log-requests: true
      log-responses: true

    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${rag-gdgs.langchain4j.open-ai.chat-model.api-key}
      model-name: qwen-plus
      log-requests: true
      log-responses: true
#    embedding-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: ${rag-gdgs.langchain4j.open-ai.chat-model.api-key}
#      model-name: text-embedding-v3
#      log-requests: true
#      log-responses: true
#      max-segments-per-batch: 10

  # 用于实现聊天记忆存储
  community:
    redis:
      host: localhost
      port: 6379



mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example: debug
#
#milvus:
#  host: localhost
#  port: 19530
#  token: root:milvus
#  database: gdgs_db
#  collection: demo_file


user:
  password-length: ${rag-gdgs.user.password-length}

jwt:
  access-expire: ${rag-gdgs.jwt.access-expire}
  refresh-expire: ${rag-gdgs.jwt.refresh-expire}
  security: ${rag-gdgs.jwt.security}


